import type { PlacementRecord } from "@/lib/placements/types";

/** Demo inventory used when Neon placements are unavailable. */
export const LOCAL_DEMO_PLACEMENTS: PlacementRecord[] = [
  {
    id: "local-placement-catalog-home-1",
    productId: "wayforpay",
    productSlug: "wayforpay",
    surface: "catalog_home",
    slotKey: "home-1",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-lg-1",
    productId: "wayforpay",
    productSlug: "wayforpay",
    surface: "map_highlight",
    slotKey: "map-lg-1",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-lg-2",
    productId: "som",
    productSlug: "som",
    surface: "map_highlight",
    slotKey: "map-lg-2",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-logo-1",
    productId: "serpstat",
    productSlug: "serpstat",
    surface: "map_logo",
    slotKey: "map-logo-1",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-logo-2",
    productId: "macpaw",
    productSlug: "macpaw",
    surface: "map_logo",
    slotKey: "map-logo-2",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-logo-3",
    productId: "kroha",
    productSlug: "kroha",
    surface: "map_logo",
    slotKey: "map-logo-3",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
  {
    id: "local-placement-map-logo-4",
    productId: "monobank",
    productSlug: "monobank",
    surface: "map_logo",
    slotKey: "map-logo-4",
    startsAt: new Date(Date.UTC(2026, 8, 1)).toISOString(),
    endsAt: new Date(Date.UTC(2027, 8, 1)).toISOString(),
    status: "active",
  },
];
